version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: sykell_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crawler
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
